# Generated by Django 2.2.1 on 2019-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190602_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
