# Generated by Django 2.2.1 on 2019-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20190602_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='macadd',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
