# Generated by Django 2.2.1 on 2019-06-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20190602_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='macadd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
