# Generated by Django 2.2.1 on 2019-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20190602_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
