# Generated by Django 2.2.1 on 2019-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20190602_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidacc',
            name='macadd',
            field=models.CharField(max_length=20),
        ),
    ]
