# Generated by Django 2.2.1 on 2019-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20190602_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidacc',
            name='macadd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
