# Generated by Django 2.2.2 on 2019-06-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20190608_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='horaA',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='horaC',
            field=models.TimeField(),
        ),
    ]
