# Generated by Django 2.2.2 on 2019-06-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_auto_20190608_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaRechazada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.FloatField()),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fktienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Tienda')),
            ],
        ),
    ]
