# Generated by Django 2.2.2 on 2019-06-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_ventarechazada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradacarro',
            name='placa',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='salidacarro',
            name='placa',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
